services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=main_database
    volumes:
      - postgres_data:/bitnami/postgresql

  postgres_test:
    image: bitnami/postgresql:latest
    restart: always
    container_name: integration-tests-prisma
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=test_database

  back_cogna:
    image: back-cogna:local
    ports:
      - '3333:3333' 
    environment:
      - NODE_ENV=production
      - PORT=3333
      - JWT_SECRET=asdasdasd
      - DATABASE_URL=postgresql://docker:docker@postgres:5432/main_database
    depends_on:
      - postgres
    restart: on-failure
    
volumes:
  postgres_data:
