name: Deploy to GKE

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: ${{ secrets.REGION }}
  CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
  REPO_NAME: ${{ secrets.REPO_NAME }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

jobs:
  deploy:
    name: Deploy Express API and DB to GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:${{ github.sha }} .
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:${{ github.sha }}

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME --region $REGION

      - name: Replace image reference in deployment
        run: |
          sed -i "s|back-cogna:local|$REGION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:${{ github.sha }}|g" k8s/*.yaml

      - name: Apply PostgreSQL and PVC first
        run: |
          kubectl apply -f k8s/postgres-pvc.yaml
          kubectl apply -f k8s/postgres.yaml
          kubectl apply -f k8s/postgres-service.yaml
          kubectl apply -f k8s/postgres-test.yaml
          kubectl apply -f k8s/postgres-test-service.yaml

      - name: Wait for DBs to be ready
        run: sleep 30

      - name: Apply Backend Deployment and Service
        run: |
          kubectl apply -f k8s/back-cogna.yaml
          kubectl apply -f k8s/back-cogna-service.yaml
