name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: 'gke-gcloud-auth-plugin' # <--- instala o plugin diretamente

      - name: Configure gcloud & get cluster credentials
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud components install gke-gcloud-auth-plugin
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }}

      - name: Authenticate Docker to GCP
        run: |
          gcloud auth configure-docker

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/back-cogna .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/back-cogna

      - name: Update backend manifest with image
        run: |
          sed -i "s|back-cogna:local|gcr.io/${{ secrets.GCP_PROJECT_ID }}/back-cogna|" k8s/back-cogna-deployment.yaml

      - name: Apply Postgres deployment
        run: |
          kubectl apply -f k8s/postgres-deployment.yaml
          kubectl rollout status deployment/postgres

      - name: Apply Backend deployment
        run: |
          kubectl apply -f k8s/back-cogna-deployment.yaml
          kubectl rollout status deployment/back-cogna
