name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy app to GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: your-gcp-project-id
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Authenticate with GKE
        run: |
          gcloud container clusters get-credentials your-cluster-name --region your-region

      - name: Build and Push Docker image
        run: |
          docker build -t gcr.io/your-gcp-project-id/back-cogna:latest .
          docker push gcr.io/your-gcp-project-id/back-cogna:latest

      - name: Replace image in manifest
        run: |
          sed -i "s|image: back-cogna:local|image: gcr.io/your-gcp-project-id/back-cogna:latest|g" k8s/back-cogna-deployment.yaml

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/
