name: Deploy to GKE

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy app to GKE
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: big-silo-423307-u7  # Atualizado aqui
          install_components: 'gke-gcloud-auth-plugin'

      - name: Authenticate with GKE
        run: |
          gcloud container clusters get-credentials autopilot-cluster-2 \
            --region us-central1 \
            --project big-silo-423307-u7

      - name: Build and Push Docker image
        run: |
          docker build -t gcr.io/back-end-cogna/back-cogna:latest .
          docker push gcr.io/back-end-cogna/back-cogna:latest

      - name: Replace image in manifest
        run: |
          sed -i "s|image: back-cogna:local|image: gcr.io/back-end-cogna/back-cogna:latest|g" k8s/back-cogna-deployment.yaml

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/