name: CI/CD - Deploy + Testes

on:
  push:
    branches:
      - master

jobs:
  build-test-deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Autenticar no GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1

      - name: Obter credenciais do cluster
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }}

      - name: Autenticar no Container Registry
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | docker login -u _json_key --password-stdin https://gcr.io

      - name: Buildar e enviar imagem do backend
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/back-cogna:latest .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/back-cogna:latest

      - name: Subir banco de testes
        run: |
          kubectl apply -f k8s/postgres-test-deployment.yaml
          kubectl rollout status deployment/postgres-test

      - name: Rodar testes E2E
        run: |
          export DATABASE_URL=postgresql://prisma:prisma@postgres-test:5433/test_database
          npm ci
          npm run test:e2e

      - name: Rodar testes unitários
        run: |
          npm run test:unit

      - name: Remover banco de testes
        if: always()
        run: |
          kubectl delete -f k8s/postgres-test-deployment.yaml

      - name: Subir banco real
        run: |
          kubectl apply -f k8s/postgres-deployment.yaml
          kubectl rollout status deployment/postgres

      - name: Subir backend
        run: |
          kubectl apply -f k8s/back-cogna-deployment.yaml
          kubectl rollout status deployment/back-cogna
